### PR TITLE
V4/trip style

### PR DESCRIPTION
**Pull request by PatrickCleary**
## Motivation

The legend on trips graphs looked a little wonky.

## Changes

Redid style for legend and download button

Screen Shot 2023-04-21 at 3 30 27 PM
Screen Shot 2023-04-21 at 3 34 56 PM
Screen Shot 2023-04-21 at 3 35 10 PM

## Testing Instructions
👀

### CODE REVIEW

**Comment by devinmatte** [comment]
Based on just the screenshots, make sure the padding on the download button and the legend leave enough room on the left and right on both travel times and dwells

**Comment by PatrickCleary** [comment]
Look good? @devinmatte 
Screen Shot 2023-04-22 at 8 13 16 AM

**Comment by devinmatte** [comment]
How does dwells look? The download button looked a little close to the left in the first screenshot?

**Comment by PatrickCleary** [comment]
Screen Shot 2023-04-22 at 8 20 32 AM
Oh yea, good call. Just fixed that

**Review by devinmatte — APPROVED** [review]
Approved from a code standpoint, can't test locally

**Pull request merged**
