### PR TITLE
Adding favicon, meta and titles

### PR DESCRIPTION
**Pull request by devinmatte**
## Motivation

Display a title, TM logo and metadata for unfurls on twitter and more

## Changes

- Adds a title to every page
- Adds metadata to actually rendered document
- Updates favicon to use the TM one, and not the vercel one

### CODE REVIEW

**Comment by PatrickCleary** [comment]
Would it be easier to wrap the whole app in `PageWrapper` and get the title from the route?

**Comment by skaplan-dev** [comment]
> Would it be easier to wrap the whole app in `PageWrapper` and get the title from the route?

+1. Is there a way to do this more programmatically with `next`?

**Comment by devinmatte** [comment]
This seems to be Next's recommended way of handling this (per route) when I was reading docs. I couldn't find a more programmatic way to handle things

**Review by PatrickCleary — APPROVED** [review]
Looks good. The icon really makes it look so much better


just one nitpick, I see a lot sites go in sort of a reverse breadcrumb order  (and use `|` as separation). So would be like `Slow Zones | Data Dashboard`. Could also do `Slow Zones | Red Line` to add even more detail.

couple examples from sites I happen to have open rn:
Screen Shot 2023-05-03 at 2 09 41 PM

**Comment by devinmatte** [comment]
Yeah I kinda agree, I'll go update the order

**Pull request merged**
