### PR TITLE
Fixes back navigation to account for date changes

### PR DESCRIPTION
**Pull request by devinmatte**
## Motivation

#712

## Changes

- Handles default loading values to not pollute history, but preserves date changes done by the user in the history

## Testing Instructions

Visit pages, hit back, make sure things feel natural and you can actually go back

### CODE REVIEW

**Comment by PatrickCleary** [comment]
Looks good, I think we should just wait to merge until we have presets and stations working with the back button as well.

**Comment by devinmatte** [comment]
That's what this fixes

**Comment by PatrickCleary** [comment]
(and the presets stay on the most recent selection if you are using those)

**Comment by devinmatte** [comment]
Okay we should all be good now

**Review by PatrickCleary — APPROVED** [review]
LGTM

**Pull request merged**
