### PR TITLE
10th and 90th percentiles and style changes.

### PR DESCRIPTION
**Pull request by PatrickCleary**
## Motivation
Add 10 and 90 percentiles to trips graphs.

#354 
#862 
#859 

Clean up fonts

Remove section from header because it's no longer necessary.

Other minor style updates.

## Changes
**Before**
Screenshot 2023-09-17 at 10 22 10 AM
**After**
Screenshot 2023-09-17 at 10 22 17 AM

**Before**
Screenshot 2023-09-17 at 10 22 50 AM
**After**
Screenshot 2023-09-17 at 10 24 35 AM

**Before**
Screenshot 2023-09-17 at 10 23 28 AM

**After**
Screenshot 2023-09-17 at 10 23 56 AM

Added 10th and 90th percentiles here:
Screenshot 2023-09-17 at 10 24 09 AM

### CODE REVIEW

**Review by devinmatte — APPROVED** [review]

**Comment by PatrickCleary** [comment]
Just realized these look funky – will fix before merge.

Screenshot 2023-09-25 at 11 09 27 AM

**Comment by devinmatte** [comment]
@PatrickCleary is this good to go?

**Comment by PatrickCleary** [comment]
Not quite. Need to address that issue in the comment above

**Comment by PatrickCleary** [comment]
@devinmatte Any idea why this build is failing? The error it's throwing is on a line that is deleted in this PR. Can see in `files changed` that it isn't there.

I can try to spend some more time debugging this later but I gotta run and idk when I'll have a chance to look at this again.

**Review by devinmatte — APPROVED** [review]

**Pull request merged**
