### PR TITLE
new favicon

### PR DESCRIPTION
**Pull request by PatrickCleary**
## Motivation

Can't use T logo.

## Changes
Before | After
Screenshot 2023-07-12 at 4 24 03 PM

### CODE REVIEW

**Comment by devinmatte** [comment]
Do we not have a higher quality PNG? 33x32px in 2023 is pretty sad looking

**Comment by PatrickCleary** [comment]
oh yea, I might've grabbed the wrong one. @mcplanner do you have the original image?

**Comment by devinmatte** [comment]
Also when you update the favicon make sure to update the `manifest.json` with the new dimensions

**Review by devinmatte — COMMENTED** [review]
We need to update `manifest.json`

```
"icons": [
    {
      "src": "favicon.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "logo.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
```

Also are we updating `logo.png`?

**Review by devinmatte — APPROVED** [review]

**Pull request merged**
