### PR TITLE
Add MbtaPerformanceAPI test to healthcheck

### PR DESCRIPTION
**Pull request by mathcolo**
- Try to grab data from realtime.mbta.com in the healthcheck
- Also print the failure reason if it exists

### CODE REVIEW

**Review by nathan-weinberg — COMMENTED** [review]
@mathcolo The new test looks good - for the handling of the functions/responses as what are your thoughts of the format I have in https://github.com/transitmatters/t-performance-dash/pull/246?

**Comment by austinjpaul** [comment]
I really like @nathan-weinberg's improvements to the checking functions. Can we adopt that portion of #246?
The check here is a good baseline. I would also want to record the response time and give a warning if it's above a certain length (say, 10s), but that might be overkill for right now.

**Comment by mathcolo** [comment]
Yep! @nathan-weinberg would you like to pull in what I have here into #246 ? Or the other way around?

**Comment by nathan-weinberg** [comment]
@mathcolo @austinjpaul I've updated https://github.com/transitmatters/t-performance-dash/pull/246 with y'alls feedback - maybe we could merge that one if it looks good then add this test afterword?

**Comment by nathan-weinberg** [comment]
I can't seem to deploy to beta as I was saying on Slack, so if someone else can deploy the PR I can verify it's working as expected.

**Comment by nathan-weinberg** [comment]
Discussed internally, changes will be incorporate into #246

**Pull request closed without merging**
