### PR TITLE
Fixed git fetch for shallow CD repo

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Tested here: https://github.com/transitmatters/t-performance-dash/actions/runs/869306247

### CODE REVIEW

**Comment by mathcolo** [comment]
So just to clarify, this addresses the possibility of the clone inside the action not actually containing the desired tag?

**Comment by nathan-weinberg** [comment]
> So just to clarify, this addresses the possibility of the clone inside the action not actually containing the desired tag?

Yes, it should now be able to deploy the latest tag to prod - the action I linked deployed the current https://dashboard-beta.transitmatters.org/ as a test

**Comment by nathan-weinberg** [comment]
@mathcolo @austinjpaul CD for the Data Dashboard is blocked until this is merged, just so y'all know

**Review by mathcolo — APPROVED** [review]
@nathan-weinberg sorry!

**Comment by nathan-weinberg** [comment]
@mathcolo np!

**Pull request merged**
