### PR TITLE
bump node to v16

### PR DESCRIPTION
**Pull request by austinjpaul**
Complete with react-scripts 5.0.0 and concurrently 7.0.0, so no more (severe) dependency issues, only moderate ones on features we're likely not using.

Probably still backwards compatible with previous nodes, but i haven't tested thoroughly. Let me know if you have issues trying to set this branch up.

### CODE REVIEW

**Review by mathcolo — APPROVED** [review]

**Review by nathan-weinberg — APPROVED** [review]
LGTM

**Comment by austinjpaul** [comment]
Hmm here's a question. Will the GitHub action run the new version of the script?

**Comment by mathcolo** [comment]
Before merge, you're asking about?

**Comment by nathan-weinberg** [comment]
The lint actions for this PR did run with the changes (i.e. Node v16 was used)

**Comment by austinjpaul** [comment]
Here goes nothing!

**Pull request merged**
